# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe0e57a6c7ba750ce2449e44c0593389d4c14afa11ba4727ceedb8d399530ac573ed4237a56f74bf04da69cce0f623d5bf9f0ac468e92d271cc5414d5b3079bd

test:
  secret_key_base: 52961453ae267e6c5ff19f547007ee325179dbb777eb27ee64ac1a15b05fd22a82bfad7bd46594d5dddfdffe0951b43186c079d997e9ea2d51092e75c952fe41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
